# Site
title: LABORATÓRIO DE EMERGÊNCIA | COVID 19
subtitle: 'SOLIDARIEDADE, EXPERIMENTAÇÃO E COLABORAÇÃO SOB CONDIÇÕES DE ISOLAMENTO'

# URL
url: https://labdeemergencia.silo.org.br
baseurl: '/1ed'
silo_url: https://silo.org.br
permalink: :categories/:title/
include: ['_pages']

# Build settings
markdown: kramdown
port: 9666
future: false

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "post"

# Data
social:
  facebook: "https://www.facebook.com/silo.arte.latitude.rural"
  instagram: "https://www.instagram.com/silo.arte.e.latitude.rural"
  github: "https://github.com/associacaosilo"
  twitter: "https://twitter.com/SiloLatitude"
  youtube: ""
  vimeo: ""
  soundcloud: ""
  tumblr: ""
  pinterest: ""
  envelope-o: "mailto:labdeemergencia@silo.org.br"
twitter_user: "SiloLatitude"
